# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_sign_cpp <- function(A) {
    .Call(`_StealLikeBayes_qr_sign_cpp`, A)
}

rhaar1 <- function(n) {
    .Call(`_StealLikeBayes_rhaar1`, n)
}

sample_variances_horseshoe <- function(x, theta, zeta, nu, varpi) {
    .Call(`_StealLikeBayes_sample_variances_horseshoe`, x, theta, zeta, nu, varpi)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_StealLikeBayes_RcppExport_registerCCallable`)
})
